language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script: |
  if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
    export PATH="$HOME/.composer/vendor/bin:$PATH"
    composer global require "phpunit/phpunit=^5.7.15"
  fi
